services:
  app:
    build: .
    working_dir: /workspace
    volumes:
      - .:/workspace
    env_file:
      - .env
    command: >
      streamlit run /workspace/src/app.py
    ports:
      - "8501:8501"